### ISSUE TITLE
Docker localhost port not working 

### ISSUE THREAD

**Issue by tywentghxst** [midarrlabs/midarr-server#162]
I used the pull request with docker and try to run it, and all I get is a can't connect to webpage, tried different installs on different ports, no connection whatsoever. Please help

**Comment by trueChazza** [comment]
Hi thanks for your query.

I'm going to need more information in order to be helpful to you:

- Pull request - what did you do here? For example did you clone repo, switch branch, run `docker compose up`
- Different installs - what did you do here? Which versions did you try, can you provide an example of your `docker-compose.yml`?

**Comment by tywentghxst** [comment]
i used the pull request from https://github.com/midarrlabs/midarr-server/pkgs/container/midarr-server


it was this docker pull ghcr.io/midarrlabs/midarr-server:latest

should i not use that?

**Comment by trueChazza** [comment]
If you ran `docker pull ghcr.io/midarrlabs/midarr-server:latest` alone, you'd just be pulling the image. You need a way of actually "using" the image/s you pull.

https://github.com/midarrlabs/midarr-server#usage
I would recommend using the provided `docker-compose.yml` as a starting point. The README details how to get started.

https://docs.docker.com/compose/compose-file/
Docker compose documentation.

**Comment by tywentghxst** [comment]
ok ill try, thankyou
